
[Variables]
GPU0colorFanRpmSelect=#colorGreen#
GPU0colorFanPerSelect=#colorWhiteDimMin#
GPU0fanMeasureName=HWiNFOGPU0FanRpm
GPU0fanUOM=rpm
GPU0memTotalMeasureName=HWiNFOGPU0MemMax
;; HWiNFOGPU0MemMax or HWiNFOGPU0MemMaxAMD
GPU0memUsedMeasureName=HWiNFOGPU0MemUsed
;; HWiNFOGPU0Mem or HWiNFOGPU0MemUsedAMD
GPU0colorAMDmemSelect=#colorWhiteDimMin#
GPU0colorNVmemSelect=#colorGreen#

GPU0SkinLoc=SimplePerfMeters\GPU0
GPU0ConfigSkinLoc=SimplePerfMeters\GPU0\config
GPU0colorFanSelectOFF=#colorWhiteDimMin#
GPU0fanDisplay=0
